### ISSUE TITLE
Arrow duping with multishot bows

### ISSUE THREAD

**Issue by tesseract-two** [OffsetMonkey538/Better-Multishot#1]
Arrows shot from a multishot regular bow can be picked up, multiplying arrows by seven. Additionally, tipped arrows are not consumed upon firing. I've reproduced this in a fresh instance with the mods listed below.

Mod list:
Better Multishot
Fabric API
Lithium
Mod Menu
No Chat Reports
No Telemetry
Sodium
Starlight

Steps to reproduce:

1. get a Multishot bow & arrows
2. fire bow
3. pick up arrows

I screenshotted the bug happening, here are some pictures:
![Screenshot_20221129_141731](https://user-images.githubusercontent.com/118913639/204627660-271007cd-e5a2-413a-a8f7-1d388268a166.png)
![Screenshot_20221129_141749](https://user-images.githubusercontent.com/118913639/204627740-7e44eb21-e845-4c8f-9153-4ead2d1fc0f6.png)
![Screenshot_20221129_141801](https://user-images.githubusercontent.com/118913639/204627760-be9e4a2f-4b81-4bee-bdd6-3d924200e9cf.png)

Thanks for this mod, it's a lot of fun to play around with!

**Comment by OffsetMonkey538** [comment]
Oh, sorry I haven't been doing much modding lately and I haven't been looking at github notifications...

Anyway, I *think* I made a fix for the problems you're having, so please try it out from [here](https://github.com/OffsetMonkey538/Better-Multishot/actions/runs/3818293767). Just scroll down and click on `artifacts` to download it. Then open the zip file and copy the file **without** `-sources` into your mods folder.

**Comment by tesseract-two** [comment]
No problem, it's fixed in that artifact. Thank you!
