### ISSUE TITLE
Mod is marked to work on 1.20.5 but it doesn't

### ISSUE THREAD

**Issue by nickademas** [OffsetMonkey538/Better-Multishot#17]
[latest.log](https://github.com/OffsetMods538/Better-Multishot/files/15094708/latest.log)
![obraz](https://github.com/OffsetMods538/Better-Multishot/assets/46594867/786a9f8e-29f2-41cd-be42-de842a53ba5a)

**Comment by OffsetMonkey538** [comment]
Oh yeah, probably did that automatically... Oh god isn't 1.20.5 like a ton of changes? I'll see what I can do

**Comment by OffsetMonkey538** [comment]
Oh boy 1.20.5 is quite the update... This might take some time to complete as I'm planning on restructuring the project to make it easier for me to work on.

**Comment by OffsetMonkey538** [comment]
Hey! I think I just might've gotten it to work. Please join my [discord](https://discord.offsetmonkey538.top), the jars are in the #chat channel under development

**Comment by OffsetMonkey538** [comment]
fixed a while ago, forgot to close
